apiVersion: v1
kind: Service
metadata:
  name: {{ template "logstash.fullname" . }}
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- with .Values.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  ports:
  {{- range .Values.exposePorts }}
  {{- if gt (int .servicePort) -1 }}
  {{- $protocol := .protocol | default "tcp" | lower }}
    - name: {{ .name | default (printf "%v-%v" $protocol .port) }}
      port: {{ .servicePort | default .port }}
      targetPort: {{ .port }}
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
      protocol: {{ $protocol | upper }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ template "logstash.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
